const actionTypes = {
    ON_LOGIN: 'ON_LOGIN',
    ON_LOGOUT: 'ON_LOGOUT',
    GET_USER_DETAILS: 'GET_USER_DETAILS',
    SET_USER_DETAILS: 'SET_USER_DETAILS',
    SET_USER_DETAIL_ERROR: 'SET_USER_DETAIL_ERROR',
    UPDATE_SPINNER: 'UPDATE_SPINNER'
}

export default actionTypes;